; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -mtriple=riscv64 -mattr=+v -passes=slp-vectorizer -S < %s | FileCheck %s

define i64 @reduce_external_16(ptr %pix, i32 %i_stride) {
; CHECK-LABEL: define i64 @reduce_external_16(
; CHECK-SAME: ptr [[PIX:%.*]], i32 [[I_STRIDE:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    [[TMP1:%.*]] = load <16 x i8>, ptr [[PIX]], align 1
; CHECK-NEXT:    [[TMP4:%.*]] = zext <16 x i8> [[TMP1]] to <16 x i32>
; CHECK-NEXT:    [[TMP5:%.*]] = mul nuw nsw <16 x i32> [[TMP4]], [[TMP4]]
; CHECK-NEXT:    [[TMP20:%.*]] = call i32 @llvm.vector.reduce.add.v16i32(<16 x i32> [[TMP4]])
; CHECK-NEXT:    [[TMP6:%.*]] = call i32 @llvm.vector.reduce.add.v16i32(<16 x i32> [[TMP5]])
; CHECK-NEXT:    [[CONV16:%.*]] = zext i32 [[TMP20]] to i64
; CHECK-NEXT:    [[CONV17:%.*]] = zext i32 [[TMP6]] to i64
; CHECK-NEXT:    [[SHL:%.*]] = shl nuw i64 [[CONV17]], 32
; CHECK-NEXT:    [[ADD17:%.*]] = or disjoint i64 [[SHL]], [[CONV16]]
; CHECK-NEXT:    ret i64 [[ADD17]]
;
  %ld = load i8, ptr %pix, align 1
  %conv = zext i8 %ld to i32
  %mul = mul nuw nsw i32 %conv, %conv
  %arrayidx.1 = getelementptr inbounds nuw i8, ptr %pix, i64 1
  %1 = load i8, ptr %arrayidx.1, align 1
  %conv.1 = zext i8 %1 to i32
  %add.1 = add i32 %conv, %conv.1
  %mul.1 = mul nuw nsw i32 %conv.1, %conv.1
  %add11.1 = add i32 %mul.1, %mul
  %arrayidx.2 = getelementptr inbounds nuw i8, ptr %pix, i64 2
  %2 = load i8, ptr %arrayidx.2, align 1
  %conv.2 = zext i8 %2 to i32
  %add.2 = add i32 %add.1, %conv.2
  %mul.2 = mul nuw nsw i32 %conv.2, %conv.2
  %add11.2 = add i32 %mul.2, %add11.1
  %arrayidx.3 = getelementptr inbounds nuw i8, ptr %pix, i64 3
  %3 = load i8, ptr %arrayidx.3, align 1
  %conv.3 = zext i8 %3 to i32
  %add.3 = add i32 %add.2, %conv.3
  %mul.3 = mul nuw nsw i32 %conv.3, %conv.3
  %add11.3 = add i32 %mul.3, %add11.2
  %arrayidx.4 = getelementptr inbounds nuw i8, ptr %pix, i64 4
  %4 = load i8, ptr %arrayidx.4, align 1
  %conv.4 = zext i8 %4 to i32
  %add.4 = add i32 %add.3, %conv.4
  %mul.4 = mul nuw nsw i32 %conv.4, %conv.4
  %add11.4 = add i32 %mul.4, %add11.3
  %arrayidx.5 = getelementptr inbounds nuw i8, ptr %pix, i64 5
  %5 = load i8, ptr %arrayidx.5, align 1
  %conv.5 = zext i8 %5 to i32
  %add.5 = add i32 %add.4, %conv.5
  %mul.5 = mul nuw nsw i32 %conv.5, %conv.5
  %add11.5 = add i32 %mul.5, %add11.4
  %arrayidx.6 = getelementptr inbounds nuw i8, ptr %pix, i64 6
  %6 = load i8, ptr %arrayidx.6, align 1
  %conv.6 = zext i8 %6 to i32
  %add.6 = add i32 %add.5, %conv.6
  %mul.6 = mul nuw nsw i32 %conv.6, %conv.6
  %add11.6 = add i32 %mul.6, %add11.5
  %arrayidx.7 = getelementptr inbounds nuw i8, ptr %pix, i64 7
  %7 = load i8, ptr %arrayidx.7, align 1
  %conv.7 = zext i8 %7 to i32
  %add.7 = add i32 %add.6, %conv.7
  %mul.7 = mul nuw nsw i32 %conv.7, %conv.7
  %add11.7 = add i32 %mul.7, %add11.6
  %arrayidx.8 = getelementptr inbounds nuw i8, ptr %pix, i64 8
  %8 = load i8, ptr %arrayidx.8, align 1
  %conv.8 = zext i8 %8 to i32
  %add.8 = add i32 %add.7, %conv.8
  %mul.8 = mul nuw nsw i32 %conv.8, %conv.8
  %add11.8 = add i32 %mul.8, %add11.7
  %arrayidx.9 = getelementptr inbounds nuw i8, ptr %pix, i64 9
  %9 = load i8, ptr %arrayidx.9, align 1
  %conv.9 = zext i8 %9 to i32
  %add.9 = add i32 %add.8, %conv.9
  %mul.9 = mul nuw nsw i32 %conv.9, %conv.9
  %add11.9 = add i32 %mul.9, %add11.8
  %arrayidx.10 = getelementptr inbounds nuw i8, ptr %pix, i64 10
  %10 = load i8, ptr %arrayidx.10, align 1
  %conv.10 = zext i8 %10 to i32
  %add.10 = add i32 %add.9, %conv.10
  %mul.10 = mul nuw nsw i32 %conv.10, %conv.10
  %add11.10 = add i32 %mul.10, %add11.9
  %arrayidx.11 = getelementptr inbounds nuw i8, ptr %pix, i64 11
  %11 = load i8, ptr %arrayidx.11, align 1
  %conv.11 = zext i8 %11 to i32
  %add.11 = add i32 %add.10, %conv.11
  %mul.11 = mul nuw nsw i32 %conv.11, %conv.11
  %add11.11 = add i32 %mul.11, %add11.10
  %arrayidx.12 = getelementptr inbounds nuw i8, ptr %pix, i64 12
  %12 = load i8, ptr %arrayidx.12, align 1
  %conv.12 = zext i8 %12 to i32
  %add.12 = add i32 %add.11, %conv.12
  %mul.12 = mul nuw nsw i32 %conv.12, %conv.12
  %add11.12 = add i32 %mul.12, %add11.11
  %arrayidx.13 = getelementptr inbounds nuw i8, ptr %pix, i64 13
  %13 = load i8, ptr %arrayidx.13, align 1
  %conv.13 = zext i8 %13 to i32
  %add.13 = add i32 %add.12, %conv.13
  %mul.13 = mul nuw nsw i32 %conv.13, %conv.13
  %add11.13 = add i32 %mul.13, %add11.12
  %arrayidx.14 = getelementptr inbounds nuw i8, ptr %pix, i64 14
  %14 = load i8, ptr %arrayidx.14, align 1
  %conv.14 = zext i8 %14 to i32
  %add.14 = add i32 %add.13, %conv.14
  %mul.14 = mul nuw nsw i32 %conv.14, %conv.14
  %add11.14 = add i32 %mul.14, %add11.13
  %arrayidx.15 = getelementptr inbounds nuw i8, ptr %pix, i64 15
  %15 = load i8, ptr %arrayidx.15, align 1
  %conv.15 = zext i8 %15 to i32
  %add.15 = add i32 %add.14, %conv.15
  %mul.15 = mul nuw nsw i32 %conv.15, %conv.15
  %add11.15 = add i32 %mul.15, %add11.14

  %conv15 = zext i32 %add.15 to i64
  %conv16 = zext i32 %add11.15 to i64
  %shl = shl nuw i64 %conv16, 32
  %add17 = or disjoint i64 %shl, %conv15
  ret i64 %add17
}

define i64 @reduce_external_8(ptr %pix, i32 %i_stride) {
; CHECK-LABEL: define i64 @reduce_external_8(
; CHECK-SAME: ptr [[PIX:%.*]], i32 [[I_STRIDE:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[TMP1:%.*]] = load <8 x i8>, ptr [[PIX]], align 1
; CHECK-NEXT:    [[TMP2:%.*]] = zext <8 x i8> [[TMP1]] to <8 x i32>
; CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <8 x i32> [[TMP2]], <8 x i32> poison, <2 x i32> <i32 0, i32 1>
; CHECK-NEXT:    [[TMP4:%.*]] = call i32 @llvm.vector.reduce.add.v2i32(<2 x i32> [[TMP3]])
; CHECK-NEXT:    [[TMP5:%.*]] = mul nuw nsw <8 x i32> [[TMP2]], [[TMP2]]
; CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i32> [[TMP2]], <8 x i32> poison, <4 x i32> <i32 2, i32 3, i32 4, i32 5>
; CHECK-NEXT:    [[TMP7:%.*]] = call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[TMP6]])
; CHECK-NEXT:    [[TMP8:%.*]] = insertelement <2 x i32> poison, i32 [[TMP7]], i32 0
; CHECK-NEXT:    [[TMP9:%.*]] = insertelement <2 x i32> [[TMP8]], i32 [[TMP4]], i32 1
; CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <8 x i32> [[TMP2]], <8 x i32> poison, <2 x i32> <i32 6, i32 7>
; CHECK-NEXT:    [[TMP11:%.*]] = add <2 x i32> [[TMP9]], [[TMP10]]
; CHECK-NEXT:    [[ADD_7:%.*]] = call i32 @llvm.vector.reduce.add.v2i32(<2 x i32> [[TMP11]])
; CHECK-NEXT:    [[ADD11_7:%.*]] = call i32 @llvm.vector.reduce.add.v8i32(<8 x i32> [[TMP5]])
; CHECK-NEXT:    [[CONV15:%.*]] = zext i32 [[ADD_7]] to i64
; CHECK-NEXT:    [[CONV16:%.*]] = zext i32 [[ADD11_7]] to i64
; CHECK-NEXT:    [[SHL:%.*]] = shl nuw i64 [[CONV16]], 32
; CHECK-NEXT:    [[ADD17:%.*]] = or disjoint i64 [[SHL]], [[CONV15]]
; CHECK-NEXT:    ret i64 [[ADD17]]
;
  %ld = load i8, ptr %pix, align 1
  %conv = zext i8 %ld to i32
  %mul = mul nuw nsw i32 %conv, %conv
  %arrayidx.1 = getelementptr inbounds nuw i8, ptr %pix, i64 1
  %1 = load i8, ptr %arrayidx.1, align 1
  %conv.1 = zext i8 %1 to i32
  %add.1 = add i32 %conv, %conv.1
  %mul.1 = mul nuw nsw i32 %conv.1, %conv.1
  %add11.1 = add i32 %mul.1, %mul
  %arrayidx.2 = getelementptr inbounds nuw i8, ptr %pix, i64 2
  %2 = load i8, ptr %arrayidx.2, align 1
  %conv.2 = zext i8 %2 to i32
  %add.2 = add i32 %add.1, %conv.2
  %mul.2 = mul nuw nsw i32 %conv.2, %conv.2
  %add11.2 = add i32 %mul.2, %add11.1
  %arrayidx.3 = getelementptr inbounds nuw i8, ptr %pix, i64 3
  %3 = load i8, ptr %arrayidx.3, align 1
  %conv.3 = zext i8 %3 to i32
  %add.3 = add i32 %add.2, %conv.3
  %mul.3 = mul nuw nsw i32 %conv.3, %conv.3
  %add11.3 = add i32 %mul.3, %add11.2
  %arrayidx.4 = getelementptr inbounds nuw i8, ptr %pix, i64 4
  %4 = load i8, ptr %arrayidx.4, align 1
  %conv.4 = zext i8 %4 to i32
  %add.4 = add i32 %add.3, %conv.4
  %mul.4 = mul nuw nsw i32 %conv.4, %conv.4
  %add11.4 = add i32 %mul.4, %add11.3
  %arrayidx.5 = getelementptr inbounds nuw i8, ptr %pix, i64 5
  %5 = load i8, ptr %arrayidx.5, align 1
  %conv.5 = zext i8 %5 to i32
  %add.5 = add i32 %add.4, %conv.5
  %mul.5 = mul nuw nsw i32 %conv.5, %conv.5
  %add11.5 = add i32 %mul.5, %add11.4
  %arrayidx.6 = getelementptr inbounds nuw i8, ptr %pix, i64 6
  %6 = load i8, ptr %arrayidx.6, align 1
  %conv.6 = zext i8 %6 to i32
  %add.6 = add i32 %add.5, %conv.6
  %mul.6 = mul nuw nsw i32 %conv.6, %conv.6
  %add11.6 = add i32 %mul.6, %add11.5
  %arrayidx.7 = getelementptr inbounds nuw i8, ptr %pix, i64 7
  %7 = load i8, ptr %arrayidx.7, align 1
  %conv.7 = zext i8 %7 to i32
  %add.7 = add i32 %add.6, %conv.7
  %mul.7 = mul nuw nsw i32 %conv.7, %conv.7
  %add11.7 = add i32 %mul.7, %add11.6

  %conv15 = zext i32 %add.7 to i64
  %conv16 = zext i32 %add11.7 to i64
  %shl = shl nuw i64 %conv16, 32
  %add17 = or disjoint i64 %shl, %conv15
  ret i64 %add17
}

define i64 @reduce_external_4(ptr %pix, i32 %i_stride) {
; CHECK-LABEL: define i64 @reduce_external_4(
; CHECK-SAME: ptr [[PIX:%.*]], i32 [[I_STRIDE:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[LD:%.*]] = load i8, ptr [[PIX]], align 1
; CHECK-NEXT:    [[ADD_5:%.*]] = zext i8 [[LD]] to i32
; CHECK-NEXT:    [[MUL:%.*]] = mul nuw nsw i32 [[ADD_5]], [[ADD_5]]
; CHECK-NEXT:    [[ARRAYIDX_1:%.*]] = getelementptr inbounds nuw i8, ptr [[PIX]], i64 1
; CHECK-NEXT:    [[TMP1:%.*]] = load i8, ptr [[ARRAYIDX_1]], align 1
; CHECK-NEXT:    [[CONV_3:%.*]] = zext i8 [[TMP1]] to i32
; CHECK-NEXT:    [[ADD_3:%.*]] = add i32 [[ADD_5]], [[CONV_3]]
; CHECK-NEXT:    [[MUL_1:%.*]] = mul nuw nsw i32 [[CONV_3]], [[CONV_3]]
; CHECK-NEXT:    [[ADD11_1:%.*]] = add i32 [[MUL_1]], [[MUL]]
; CHECK-NEXT:    [[ARRAYIDX_2:%.*]] = getelementptr inbounds nuw i8, ptr [[PIX]], i64 2
; CHECK-NEXT:    [[TMP2:%.*]] = load i8, ptr [[ARRAYIDX_2]], align 1
; CHECK-NEXT:    [[CONV_2:%.*]] = zext i8 [[TMP2]] to i32
; CHECK-NEXT:    [[ADD_2:%.*]] = add i32 [[ADD_3]], [[CONV_2]]
; CHECK-NEXT:    [[MUL_2:%.*]] = mul nuw nsw i32 [[CONV_2]], [[CONV_2]]
; CHECK-NEXT:    [[ADD11_2:%.*]] = add i32 [[MUL_2]], [[ADD11_1]]
; CHECK-NEXT:    [[ARRAYIDX_3:%.*]] = getelementptr inbounds nuw i8, ptr [[PIX]], i64 3
; CHECK-NEXT:    [[TMP3:%.*]] = load i8, ptr [[ARRAYIDX_3]], align 1
; CHECK-NEXT:    [[CONV_5:%.*]] = zext i8 [[TMP3]] to i32
; CHECK-NEXT:    [[ADD_6:%.*]] = add i32 [[ADD_2]], [[CONV_5]]
; CHECK-NEXT:    [[MUL_3:%.*]] = mul nuw nsw i32 [[CONV_5]], [[CONV_5]]
; CHECK-NEXT:    [[ADD11_3:%.*]] = add i32 [[MUL_3]], [[ADD11_2]]
; CHECK-NEXT:    [[ARRAYIDX_4:%.*]] = getelementptr inbounds nuw i8, ptr [[PIX]], i64 4
; CHECK-NEXT:    [[TMP4:%.*]] = load i8, ptr [[ARRAYIDX_4]], align 1
; CHECK-NEXT:    [[CONV_4:%.*]] = zext i8 [[TMP4]] to i32
; CHECK-NEXT:    [[ADD_4:%.*]] = add i32 [[ADD_6]], [[CONV_4]]
; CHECK-NEXT:    [[MUL_4:%.*]] = mul nuw nsw i32 [[CONV_4]], [[CONV_4]]
; CHECK-NEXT:    [[ADD11_4:%.*]] = add i32 [[MUL_4]], [[ADD11_3]]
; CHECK-NEXT:    [[CONV15:%.*]] = zext i32 [[ADD_4]] to i64
; CHECK-NEXT:    [[CONV16:%.*]] = zext i32 [[ADD11_4]] to i64
; CHECK-NEXT:    [[SHL:%.*]] = shl nuw i64 [[CONV16]], 32
; CHECK-NEXT:    [[ADD17:%.*]] = or disjoint i64 [[SHL]], [[CONV15]]
; CHECK-NEXT:    ret i64 [[ADD17]]
;
  %ld = load i8, ptr %pix, align 1
  %conv = zext i8 %ld to i32
  %mul = mul nuw nsw i32 %conv, %conv
  %arrayidx.1 = getelementptr inbounds nuw i8, ptr %pix, i64 1
  %1 = load i8, ptr %arrayidx.1, align 1
  %conv.1 = zext i8 %1 to i32
  %add.1 = add i32 %conv, %conv.1
  %mul.1 = mul nuw nsw i32 %conv.1, %conv.1
  %add11.1 = add i32 %mul.1, %mul
  %arrayidx.2 = getelementptr inbounds nuw i8, ptr %pix, i64 2
  %2 = load i8, ptr %arrayidx.2, align 1
  %conv.2 = zext i8 %2 to i32
  %add.2 = add i32 %add.1, %conv.2
  %mul.2 = mul nuw nsw i32 %conv.2, %conv.2
  %add11.2 = add i32 %mul.2, %add11.1
  %arrayidx.3 = getelementptr inbounds nuw i8, ptr %pix, i64 3
  %3 = load i8, ptr %arrayidx.3, align 1
  %conv.3 = zext i8 %3 to i32
  %add.3 = add i32 %add.2, %conv.3
  %mul.3 = mul nuw nsw i32 %conv.3, %conv.3
  %add11.3 = add i32 %mul.3, %add11.2
  %arrayidx.4 = getelementptr inbounds nuw i8, ptr %pix, i64 4
  %4 = load i8, ptr %arrayidx.4, align 1
  %conv.4 = zext i8 %4 to i32
  %add.4 = add i32 %add.3, %conv.4
  %mul.4 = mul nuw nsw i32 %conv.4, %conv.4
  %add11.4 = add i32 %mul.4, %add11.3

  %conv15 = zext i32 %add.4 to i64
  %conv16 = zext i32 %add11.4 to i64
  %shl = shl nuw i64 %conv16, 32
  %add17 = or disjoint i64 %shl, %conv15
  ret i64 %add17
}
