; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=slp-vectorizer -S < %s -mtriple=riscv32 -mattr=+v -slp-threshold=-50 | FileCheck %s

define void @phantom_shl(ptr noalias %l, ptr noalias %s) {
; CHECK-LABEL: @phantom_shl(
; CHECK-NEXT:    [[LPTR0:%.*]] = getelementptr i32, ptr [[L:%.*]], i32 0
; CHECK-NEXT:    [[SPTR0:%.*]] = getelementptr i32, ptr [[S:%.*]], i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = load <8 x i32>, ptr [[LPTR0]], align 4
; CHECK-NEXT:    [[TMP2:%.*]] = shl <8 x i32> [[TMP1]], <i32 8, i32 8, i32 8, i32 8, i32 8, i32 8, i32 8, i32 0>
; CHECK-NEXT:    store <8 x i32> [[TMP2]], ptr [[SPTR0]], align 4
; CHECK-NEXT:    ret void
;
  %lptr0 = getelementptr i32, ptr %l, i32 0
  %lptr1 = getelementptr i32, ptr %l, i32 1
  %lptr2 = getelementptr i32, ptr %l, i32 2
  %lptr3 = getelementptr i32, ptr %l, i32 3
  %lptr4 = getelementptr i32, ptr %l, i32 4
  %lptr5 = getelementptr i32, ptr %l, i32 5
  %lptr6 = getelementptr i32, ptr %l, i32 6
  %lptr7 = getelementptr i32, ptr %l, i32 7

  %sptr0 = getelementptr i32, ptr %s, i32 0
  %sptr1 = getelementptr i32, ptr %s, i32 1
  %sptr2 = getelementptr i32, ptr %s, i32 2
  %sptr3 = getelementptr i32, ptr %s, i32 3
  %sptr4 = getelementptr i32, ptr %s, i32 4
  %sptr5 = getelementptr i32, ptr %s, i32 5
  %sptr6 = getelementptr i32, ptr %s, i32 6
  %sptr7 = getelementptr i32, ptr %s, i32 7

  %load0 = load i32, ptr %lptr0
  %load1 = load i32, ptr %lptr1
  %load2 = load i32, ptr %lptr2
  %load3 = load i32, ptr %lptr3
  %load4 = load i32, ptr %lptr4
  %load5 = load i32, ptr %lptr5
  %load6 = load i32, ptr %lptr6
  %load7 = load i32, ptr %lptr7

  %op0 = shl i32 %load0, 8
  %op1 = shl i32 %load1, 8
  %op2 = shl i32 %load2, 8
  %op3 = shl i32 %load3, 8
  %op4 = shl i32 %load4, 8
  %op5 = shl i32 %load5, 8
  %op6 = shl i32 %load6, 8
; %op7 = shl i32 %load7, 0 <-- missing phantom shift

  store i32 %op0, ptr %sptr0
  store i32 %op1, ptr %sptr1
  store i32 %op2, ptr %sptr2
  store i32 %op3, ptr %sptr3
  store i32 %op4, ptr %sptr4
  store i32 %op5, ptr %sptr5
  store i32 %op6, ptr %sptr6
  store i32 %load7, ptr %sptr7
  ret void
}

define void @phantom_ashr(ptr noalias %l, ptr noalias %s) {
; CHECK-LABEL: @phantom_ashr(
; CHECK-NEXT:    [[LPTR0:%.*]] = getelementptr i32, ptr [[L:%.*]], i32 0
; CHECK-NEXT:    [[SPTR0:%.*]] = getelementptr i32, ptr [[S:%.*]], i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = load <8 x i32>, ptr [[LPTR0]], align 4
; CHECK-NEXT:    [[TMP2:%.*]] = ashr <8 x i32> [[TMP1]], <i32 8, i32 8, i32 8, i32 8, i32 8, i32 8, i32 8, i32 0>
; CHECK-NEXT:    store <8 x i32> [[TMP2]], ptr [[SPTR0]], align 4
; CHECK-NEXT:    ret void
;
  %lptr0 = getelementptr i32, ptr %l, i32 0
  %lptr1 = getelementptr i32, ptr %l, i32 1
  %lptr2 = getelementptr i32, ptr %l, i32 2
  %lptr3 = getelementptr i32, ptr %l, i32 3
  %lptr4 = getelementptr i32, ptr %l, i32 4
  %lptr5 = getelementptr i32, ptr %l, i32 5
  %lptr6 = getelementptr i32, ptr %l, i32 6
  %lptr7 = getelementptr i32, ptr %l, i32 7

  %sptr0 = getelementptr i32, ptr %s, i32 0
  %sptr1 = getelementptr i32, ptr %s, i32 1
  %sptr2 = getelementptr i32, ptr %s, i32 2
  %sptr3 = getelementptr i32, ptr %s, i32 3
  %sptr4 = getelementptr i32, ptr %s, i32 4
  %sptr5 = getelementptr i32, ptr %s, i32 5
  %sptr6 = getelementptr i32, ptr %s, i32 6
  %sptr7 = getelementptr i32, ptr %s, i32 7

  %load0 = load i32, ptr %lptr0
  %load1 = load i32, ptr %lptr1
  %load2 = load i32, ptr %lptr2
  %load3 = load i32, ptr %lptr3
  %load4 = load i32, ptr %lptr4
  %load5 = load i32, ptr %lptr5
  %load6 = load i32, ptr %lptr6
  %load7 = load i32, ptr %lptr7

  %op0 = ashr i32 %load0, 8
  %op1 = ashr i32 %load1, 8
  %op2 = ashr i32 %load2, 8
  %op3 = ashr i32 %load3, 8
  %op4 = ashr i32 %load4, 8
  %op5 = ashr i32 %load5, 8
  %op6 = ashr i32 %load6, 8
  %op7 = ashr i32 %load7, 0

  store i32 %op0, ptr %sptr0
  store i32 %op1, ptr %sptr1
  store i32 %op2, ptr %sptr2
  store i32 %op3, ptr %sptr3
  store i32 %op4, ptr %sptr4
  store i32 %op5, ptr %sptr5
  store i32 %op6, ptr %sptr6
  store i32 %op7, ptr %sptr7
  ret void
}

define void @phantom_lshr(ptr noalias %l, ptr noalias %s) {
; CHECK-LABEL: @phantom_lshr(
; CHECK-NEXT:    [[LPTR0:%.*]] = getelementptr i32, ptr [[L:%.*]], i32 0
; CHECK-NEXT:    [[SPTR0:%.*]] = getelementptr i32, ptr [[S:%.*]], i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = load <8 x i32>, ptr [[LPTR0]], align 4
; CHECK-NEXT:    [[TMP2:%.*]] = lshr <8 x i32> [[TMP1]], <i32 8, i32 8, i32 8, i32 8, i32 8, i32 8, i32 8, i32 0>
; CHECK-NEXT:    store <8 x i32> [[TMP2]], ptr [[SPTR0]], align 4
; CHECK-NEXT:    ret void
;
  %lptr0 = getelementptr i32, ptr %l, i32 0
  %lptr1 = getelementptr i32, ptr %l, i32 1
  %lptr2 = getelementptr i32, ptr %l, i32 2
  %lptr3 = getelementptr i32, ptr %l, i32 3
  %lptr4 = getelementptr i32, ptr %l, i32 4
  %lptr5 = getelementptr i32, ptr %l, i32 5
  %lptr6 = getelementptr i32, ptr %l, i32 6
  %lptr7 = getelementptr i32, ptr %l, i32 7

  %sptr0 = getelementptr i32, ptr %s, i32 0
  %sptr1 = getelementptr i32, ptr %s, i32 1
  %sptr2 = getelementptr i32, ptr %s, i32 2
  %sptr3 = getelementptr i32, ptr %s, i32 3
  %sptr4 = getelementptr i32, ptr %s, i32 4
  %sptr5 = getelementptr i32, ptr %s, i32 5
  %sptr6 = getelementptr i32, ptr %s, i32 6
  %sptr7 = getelementptr i32, ptr %s, i32 7

  %load0 = load i32, ptr %lptr0
  %load1 = load i32, ptr %lptr1
  %load2 = load i32, ptr %lptr2
  %load3 = load i32, ptr %lptr3
  %load4 = load i32, ptr %lptr4
  %load5 = load i32, ptr %lptr5
  %load6 = load i32, ptr %lptr6
  %load7 = load i32, ptr %lptr7

  %op0 = lshr i32 %load0, 8
  %op1 = lshr i32 %load1, 8
  %op2 = lshr i32 %load2, 8
  %op3 = lshr i32 %load3, 8
  %op4 = lshr i32 %load4, 8
  %op5 = lshr i32 %load5, 8
  %op6 = lshr i32 %load6, 8
; %op7 = lshr i32 %load7, 0 <-- missing phantom shift

  store i32 %op0, ptr %sptr0
  store i32 %op1, ptr %sptr1
  store i32 %op2, ptr %sptr2
  store i32 %op3, ptr %sptr3
  store i32 %op4, ptr %sptr4
  store i32 %op5, ptr %sptr5
  store i32 %op6, ptr %sptr6
  store i32 %load7, ptr %sptr7
  ret void
}
