; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -mtriple=riscv64 -mcpu=sifive-p870 -passes=slp-vectorizer -S -slp-revec -slp-threshold=-100 %s | FileCheck %s

; Base case of strided load, implicitly is widened
define void @widened_strided_load(ptr %in0, ptr %out0) {
; CHECK-LABEL: @widened_strided_load(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP1:%.*]] = call <2 x i64> @llvm.experimental.vp.strided.load.v2i64.p0.i64(ptr align 2 [[IN0:%.*]], i64 16, <2 x i1> splat (i1 true), i32 2)
; CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i64> [[TMP1]] to <16 x i8>
; CHECK-NEXT:    store <16 x i8> [[TMP0]], ptr [[OUT0:%.*]], align 2
; CHECK-NEXT:    ret void
;
entry:
  %in1 = getelementptr i8, ptr %in0, i64 16
  %l0 = load <8 x i8>, ptr %in0, align 2
  %l1 = load <8 x i8>, ptr %in1, align 2
  %out1 = getelementptr i8, ptr %out0, i64 8
  store <8 x i8> %l0, ptr %out0, align 2
  store <8 x i8> %l1, ptr %out1, align 2
  ret void
}

