; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5

; RUN: opt -mtriple=riscv64 -mattr=+m,+v -passes=slp-vectorizer -S -slp-enable-strided-stores -slp-threshold=-100 -slp-revec < %s | FileCheck %s

define void @runtime_stride(ptr %pl, ptr %ps, i64 %stride) {
; CHECK-LABEL: define void @runtime_stride(
; CHECK-SAME: ptr [[PL:%.*]], ptr [[PS:%.*]], i64 [[STRIDE:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    [[GEP_L0:%.*]] = getelementptr i8, ptr [[PL]], i64 0
; CHECK-NEXT:    [[GEP_L1:%.*]] = getelementptr i8, ptr [[PL]], i64 1
; CHECK-NEXT:    [[GEP_L2:%.*]] = getelementptr i8, ptr [[PL]], i64 2
; CHECK-NEXT:    [[GEP_L3:%.*]] = getelementptr i8, ptr [[PL]], i64 3
; CHECK-NEXT:    [[GEP_L4:%.*]] = getelementptr i8, ptr [[PL]], i64 4
; CHECK-NEXT:    [[GEP_L5:%.*]] = getelementptr i8, ptr [[PL]], i64 5
; CHECK-NEXT:    [[GEP_L6:%.*]] = getelementptr i8, ptr [[PL]], i64 6
; CHECK-NEXT:    [[GEP_L7:%.*]] = getelementptr i8, ptr [[PL]], i64 7
; CHECK-NEXT:    [[TMP9:%.*]] = load i8, ptr [[GEP_L7]], align 1
; CHECK-NEXT:    [[TMP8:%.*]] = load i8, ptr [[GEP_L6]], align 1
; CHECK-NEXT:    [[TMP7:%.*]] = load i8, ptr [[GEP_L5]], align 1
; CHECK-NEXT:    [[TMP6:%.*]] = load i8, ptr [[GEP_L4]], align 1
; CHECK-NEXT:    [[TMP5:%.*]] = load i8, ptr [[GEP_L3]], align 1
; CHECK-NEXT:    [[TMP4:%.*]] = load i8, ptr [[GEP_L2]], align 1
; CHECK-NEXT:    [[TMP3:%.*]] = load i8, ptr [[GEP_L1]], align 1
; CHECK-NEXT:    [[TMP2:%.*]] = load i8, ptr [[GEP_L0]], align 1
; CHECK-NEXT:    [[GEP_S0:%.*]] = getelementptr i8, ptr [[PS]], i64 0
; CHECK-NEXT:    [[GEP_S1:%.*]] = getelementptr i8, ptr [[GEP_S0]], i64 [[STRIDE]]
; CHECK-NEXT:    [[GEP_S2:%.*]] = getelementptr i8, ptr [[GEP_S1]], i64 [[STRIDE]]
; CHECK-NEXT:    [[GEP_S3:%.*]] = getelementptr i8, ptr [[GEP_S2]], i64 [[STRIDE]]
; CHECK-NEXT:    [[GEP_S4:%.*]] = getelementptr i8, ptr [[GEP_S3]], i64 [[STRIDE]]
; CHECK-NEXT:    [[GEP_S5:%.*]] = getelementptr i8, ptr [[GEP_S4]], i64 [[STRIDE]]
; CHECK-NEXT:    [[GEP_S6:%.*]] = getelementptr i8, ptr [[GEP_S5]], i64 [[STRIDE]]
; CHECK-NEXT:    [[GEP_S7:%.*]] = getelementptr i8, ptr [[GEP_S6]], i64 [[STRIDE]]
; CHECK-NEXT:    store i8 [[TMP2]], ptr [[GEP_S0]], align 1
; CHECK-NEXT:    store i8 [[TMP3]], ptr [[GEP_S1]], align 1
; CHECK-NEXT:    store i8 [[TMP4]], ptr [[GEP_S2]], align 1
; CHECK-NEXT:    store i8 [[TMP5]], ptr [[GEP_S3]], align 1
; CHECK-NEXT:    store i8 [[TMP6]], ptr [[GEP_S4]], align 1
; CHECK-NEXT:    store i8 [[TMP7]], ptr [[GEP_S5]], align 1
; CHECK-NEXT:    store i8 [[TMP8]], ptr [[GEP_S6]], align 1
; CHECK-NEXT:    store i8 [[TMP9]], ptr [[GEP_S7]], align 1
; CHECK-NEXT:    ret void
;
  %gep_l0 = getelementptr i8, ptr %pl, i64 0
  %gep_l1 = getelementptr i8, ptr %pl, i64 1
  %gep_l2 = getelementptr i8, ptr %pl, i64 2
  %gep_l3 = getelementptr i8, ptr %pl, i64 3
  %gep_l4 = getelementptr i8, ptr %pl, i64 4
  %gep_l5 = getelementptr i8, ptr %pl, i64 5
  %gep_l6 = getelementptr i8, ptr %pl, i64 6
  %gep_l7 = getelementptr i8, ptr %pl, i64 7

  %load0  = load i8, ptr %gep_l0
  %load1  = load i8, ptr %gep_l1
  %load2  = load i8, ptr %gep_l2
  %load3  = load i8, ptr %gep_l3
  %load4  = load i8, ptr %gep_l4
  %load5  = load i8, ptr %gep_l5
  %load6  = load i8, ptr %gep_l6
  %load7  = load i8, ptr %gep_l7

  %gep_s0 = getelementptr i8, ptr %ps, i64 0
  %gep_s1 = getelementptr i8, ptr %gep_s0, i64 %stride
  %gep_s2 = getelementptr i8, ptr %gep_s1, i64 %stride
  %gep_s3 = getelementptr i8, ptr %gep_s2, i64 %stride
  %gep_s4 = getelementptr i8, ptr %gep_s3, i64 %stride
  %gep_s5 = getelementptr i8, ptr %gep_s4, i64 %stride
  %gep_s6 = getelementptr i8, ptr %gep_s5, i64 %stride
  %gep_s7 = getelementptr i8, ptr %gep_s6, i64 %stride

  store i8 %load0, ptr %gep_s0
  store i8 %load1, ptr %gep_s1
  store i8 %load2, ptr %gep_s2
  store i8 %load3, ptr %gep_s3
  store i8 %load4, ptr %gep_s4
  store i8 %load5, ptr %gep_s5
  store i8 %load6, ptr %gep_s6
  store i8 %load7, ptr %gep_s7

  ret void
}
