; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5

; RUN: opt -mtriple=riscv64 -mattr=+m,+v,+unaligned-vector-mem -passes=slp-vectorizer -S < %s | FileCheck %s

define void @unaligned_const_stride(ptr %pl, ptr %ps) {
; CHECK-LABEL: define void @unaligned_const_stride(
; CHECK-SAME: ptr [[PL:%.*]], ptr [[PS:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    [[TMP1:%.*]] = insertelement <8 x ptr> poison, ptr [[PL]], i32 0
; CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x ptr> [[TMP1]], <8 x ptr> poison, <8 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, <8 x ptr> [[TMP2]], <8 x i64> <i64 0, i64 65, i64 130, i64 195, i64 260, i64 325, i64 390, i64 455>
; CHECK-NEXT:    [[GEP_S0:%.*]] = getelementptr inbounds i16, ptr [[PS]], i64 0
; CHECK-NEXT:    [[TMP4:%.*]] = call <8 x i16> @llvm.masked.gather.v8i16.v8p0(<8 x ptr> align 1 [[TMP3]], <8 x i1> splat (i1 true), <8 x i16> poison)
; CHECK-NEXT:    store <8 x i16> [[TMP4]], ptr [[GEP_S0]], align 1
; CHECK-NEXT:    ret void
;
  %gep_l0 = getelementptr inbounds i8, ptr %pl, i64 0
  %gep_l1 = getelementptr inbounds i8, ptr %pl, i64 65
  %gep_l2 = getelementptr inbounds i8, ptr %pl, i64 130
  %gep_l3 = getelementptr inbounds i8, ptr %pl, i64 195
  %gep_l4 = getelementptr inbounds i8, ptr %pl, i64 260
  %gep_l5 = getelementptr inbounds i8, ptr %pl, i64 325
  %gep_l6 = getelementptr inbounds i8, ptr %pl, i64 390
  %gep_l7 = getelementptr inbounds i8, ptr %pl, i64 455

  %load0  = load i16, ptr %gep_l0 , align 1
  %load1  = load i16, ptr %gep_l1 , align 1
  %load2  = load i16, ptr %gep_l2 , align 1
  %load3  = load i16, ptr %gep_l3 , align 1
  %load4  = load i16, ptr %gep_l4 , align 1
  %load5  = load i16, ptr %gep_l5 , align 1
  %load6  = load i16, ptr %gep_l6 , align 1
  %load7  = load i16, ptr %gep_l7 , align 1

  %gep_s0 = getelementptr inbounds i16, ptr %ps, i64 0
  %gep_s1 = getelementptr inbounds i16, ptr %ps, i64 1
  %gep_s2 = getelementptr inbounds i16, ptr %ps, i64 2
  %gep_s3 = getelementptr inbounds i16, ptr %ps, i64 3
  %gep_s4 = getelementptr inbounds i16, ptr %ps, i64 4
  %gep_s5 = getelementptr inbounds i16, ptr %ps, i64 5
  %gep_s6 = getelementptr inbounds i16, ptr %ps, i64 6
  %gep_s7 = getelementptr inbounds i16, ptr %ps, i64 7

  store i16 %load0, ptr %gep_s0, align 1
  store i16 %load1, ptr %gep_s1, align 1
  store i16 %load2, ptr %gep_s2, align 1
  store i16 %load3, ptr %gep_s3, align 1
  store i16 %load4, ptr %gep_s4, align 1
  store i16 %load5, ptr %gep_s5, align 1
  store i16 %load6, ptr %gep_s6, align 1
  store i16 %load7, ptr %gep_s7, align 1

  ret void
}

define void @rt_stride_1_no_reordering(ptr %pl, i64 %stride, ptr %ps) {
; CHECK-LABEL: define void @rt_stride_1_no_reordering(
; CHECK-SAME: ptr [[PL:%.*]], i64 [[STRIDE:%.*]], ptr [[PS:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[TMP1:%.*]] = insertelement <8 x i64> poison, i64 [[STRIDE]], i32 0
; CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x i64> [[TMP1]], <8 x i64> poison, <8 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP3:%.*]] = mul nsw <8 x i64> [[TMP2]], <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7>
; CHECK-NEXT:    [[STRIDE14:%.*]] = mul nsw i64 [[STRIDE]], 8
; CHECK-NEXT:    [[STRIDE8:%.*]] = mul nsw i64 [[STRIDE]], 9
; CHECK-NEXT:    [[STRIDE10:%.*]] = mul nsw i64 [[STRIDE]], 10
; CHECK-NEXT:    [[STRIDE11:%.*]] = mul nsw i64 [[STRIDE]], 11
; CHECK-NEXT:    [[STRIDE12:%.*]] = mul nsw i64 [[STRIDE]], 12
; CHECK-NEXT:    [[STRIDE13:%.*]] = mul nsw i64 [[STRIDE]], 13
; CHECK-NEXT:    [[STRIDE16:%.*]] = mul nsw i64 [[STRIDE]], 14
; CHECK-NEXT:    [[STRIDE15:%.*]] = mul nsw i64 [[STRIDE]], 15
; CHECK-NEXT:    [[GEP_L14:%.*]] = getelementptr inbounds i16, ptr [[PL]], i64 [[STRIDE14]]
; CHECK-NEXT:    [[GEP_L8:%.*]] = getelementptr inbounds i16, ptr [[PL]], i64 [[STRIDE8]]
; CHECK-NEXT:    [[GEP_L10:%.*]] = getelementptr inbounds i16, ptr [[PL]], i64 [[STRIDE10]]
; CHECK-NEXT:    [[GEP_L11:%.*]] = getelementptr inbounds i16, ptr [[PL]], i64 [[STRIDE11]]
; CHECK-NEXT:    [[GEP_L12:%.*]] = getelementptr inbounds i16, ptr [[PL]], i64 [[STRIDE12]]
; CHECK-NEXT:    [[GEP_L13:%.*]] = getelementptr inbounds i16, ptr [[PL]], i64 [[STRIDE13]]
; CHECK-NEXT:    [[GEP_L16:%.*]] = getelementptr inbounds i16, ptr [[PL]], i64 [[STRIDE16]]
; CHECK-NEXT:    [[GEP_L15:%.*]] = getelementptr inbounds i16, ptr [[PL]], i64 [[STRIDE15]]
; CHECK-NEXT:    [[LOAD8:%.*]] = load i32, ptr [[GEP_L14]], align 1
; CHECK-NEXT:    [[LOAD9:%.*]] = load i32, ptr [[GEP_L8]], align 1
; CHECK-NEXT:    [[LOAD10:%.*]] = load i32, ptr [[GEP_L10]], align 1
; CHECK-NEXT:    [[LOAD11:%.*]] = load i32, ptr [[GEP_L11]], align 1
; CHECK-NEXT:    [[LOAD12:%.*]] = load i32, ptr [[GEP_L12]], align 1
; CHECK-NEXT:    [[LOAD13:%.*]] = load i32, ptr [[GEP_L13]], align 1
; CHECK-NEXT:    [[LOAD14:%.*]] = load i32, ptr [[GEP_L16]], align 1
; CHECK-NEXT:    [[LOAD15:%.*]] = load i32, ptr [[GEP_L15]], align 1
; CHECK-NEXT:    [[GEP_S0:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 0
; CHECK-NEXT:    [[GEP_S8:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 8
; CHECK-NEXT:    [[GEP_S9:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 9
; CHECK-NEXT:    [[GEP_S10:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 10
; CHECK-NEXT:    [[GEP_S11:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 11
; CHECK-NEXT:    [[GEP_S12:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 12
; CHECK-NEXT:    [[GEP_S13:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 13
; CHECK-NEXT:    [[GEP_S14:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 14
; CHECK-NEXT:    [[GEP_S15:%.*]] = getelementptr inbounds i32, ptr [[PS]], i64 15
; CHECK-NEXT:    [[TMP4:%.*]] = insertelement <8 x ptr> poison, ptr [[PL]], i32 0
; CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <8 x ptr> [[TMP4]], <8 x ptr> poison, <8 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr i16, <8 x ptr> [[TMP5]], <8 x i64> [[TMP3]]
; CHECK-NEXT:    [[TMP7:%.*]] = call <8 x i32> @llvm.masked.gather.v8i32.v8p0(<8 x ptr> align 1 [[TMP6]], <8 x i1> splat (i1 true), <8 x i32> poison)
; CHECK-NEXT:    store <8 x i32> [[TMP7]], ptr [[GEP_S0]], align 1
; CHECK-NEXT:    store i32 [[LOAD8]], ptr [[GEP_S8]], align 1
; CHECK-NEXT:    store i32 [[LOAD9]], ptr [[GEP_S9]], align 1
; CHECK-NEXT:    store i32 [[LOAD10]], ptr [[GEP_S10]], align 1
; CHECK-NEXT:    store i32 [[LOAD11]], ptr [[GEP_S11]], align 1
; CHECK-NEXT:    store i32 [[LOAD12]], ptr [[GEP_S12]], align 1
; CHECK-NEXT:    store i32 [[LOAD13]], ptr [[GEP_S13]], align 1
; CHECK-NEXT:    store i32 [[LOAD14]], ptr [[GEP_S14]], align 1
; CHECK-NEXT:    store i32 [[LOAD15]], ptr [[GEP_S15]], align 1
; CHECK-NEXT:    ret void
;
  %stride0  = mul nsw i64 %stride, 0
  %stride1  = mul nsw i64 %stride, 1
  %stride2  = mul nsw i64 %stride, 2
  %stride3  = mul nsw i64 %stride, 3
  %stride4  = mul nsw i64 %stride, 4
  %stride5  = mul nsw i64 %stride, 5
  %stride6  = mul nsw i64 %stride, 6
  %stride7  = mul nsw i64 %stride, 7
  %stride8  = mul nsw i64 %stride, 8
  %stride9  = mul nsw i64 %stride, 9
  %stride10 = mul nsw i64 %stride, 10
  %stride11 = mul nsw i64 %stride, 11
  %stride12 = mul nsw i64 %stride, 12
  %stride13 = mul nsw i64 %stride, 13
  %stride14 = mul nsw i64 %stride, 14
  %stride15 = mul nsw i64 %stride, 15

  %gep_l0 = getelementptr inbounds i16, ptr %pl, i64 %stride0
  %gep_l1 = getelementptr inbounds i16, ptr %pl, i64 %stride1
  %gep_l2 = getelementptr inbounds i16, ptr %pl, i64 %stride2
  %gep_l3 = getelementptr inbounds i16, ptr %pl, i64 %stride3
  %gep_l4 = getelementptr inbounds i16, ptr %pl, i64 %stride4
  %gep_l5 = getelementptr inbounds i16, ptr %pl, i64 %stride5
  %gep_l6 = getelementptr inbounds i16, ptr %pl, i64 %stride6
  %gep_l7 = getelementptr inbounds i16, ptr %pl, i64 %stride7
  %gep_l8 = getelementptr inbounds i16, ptr %pl, i64 %stride8
  %gep_l9 = getelementptr inbounds i16, ptr %pl, i64 %stride9
  %gep_l10 = getelementptr inbounds i16, ptr %pl, i64 %stride10
  %gep_l11 = getelementptr inbounds i16, ptr %pl, i64 %stride11
  %gep_l12 = getelementptr inbounds i16, ptr %pl, i64 %stride12
  %gep_l13 = getelementptr inbounds i16, ptr %pl, i64 %stride13
  %gep_l14 = getelementptr inbounds i16, ptr %pl, i64 %stride14
  %gep_l15 = getelementptr inbounds i16, ptr %pl, i64 %stride15

  %load0  = load i32, ptr %gep_l0 , align 1
  %load1  = load i32, ptr %gep_l1 , align 1
  %load2  = load i32, ptr %gep_l2 , align 1
  %load3  = load i32, ptr %gep_l3 , align 1
  %load4  = load i32, ptr %gep_l4 , align 1
  %load5  = load i32, ptr %gep_l5 , align 1
  %load6  = load i32, ptr %gep_l6 , align 1
  %load7  = load i32, ptr %gep_l7 , align 1
  %load8  = load i32, ptr %gep_l8 , align 1
  %load9  = load i32, ptr %gep_l9 , align 1
  %load10 = load i32, ptr %gep_l10, align 1
  %load11 = load i32, ptr %gep_l11, align 1
  %load12 = load i32, ptr %gep_l12, align 1
  %load13 = load i32, ptr %gep_l13, align 1
  %load14 = load i32, ptr %gep_l14, align 1
  %load15 = load i32, ptr %gep_l15, align 1

  %gep_s0 = getelementptr inbounds i32, ptr %ps, i64 0
  %gep_s1 = getelementptr inbounds i32, ptr %ps, i64 1
  %gep_s2 = getelementptr inbounds i32, ptr %ps, i64 2
  %gep_s3 = getelementptr inbounds i32, ptr %ps, i64 3
  %gep_s4 = getelementptr inbounds i32, ptr %ps, i64 4
  %gep_s5 = getelementptr inbounds i32, ptr %ps, i64 5
  %gep_s6 = getelementptr inbounds i32, ptr %ps, i64 6
  %gep_s7 = getelementptr inbounds i32, ptr %ps, i64 7
  %gep_s8 = getelementptr inbounds i32, ptr %ps, i64 8
  %gep_s9 = getelementptr inbounds i32, ptr %ps, i64 9
  %gep_s10 = getelementptr inbounds i32, ptr %ps, i64 10
  %gep_s11 = getelementptr inbounds i32, ptr %ps, i64 11
  %gep_s12 = getelementptr inbounds i32, ptr %ps, i64 12
  %gep_s13 = getelementptr inbounds i32, ptr %ps, i64 13
  %gep_s14 = getelementptr inbounds i32, ptr %ps, i64 14
  %gep_s15 = getelementptr inbounds i32, ptr %ps, i64 15

  store i32 %load0, ptr %gep_s0, align 1
  store i32 %load1, ptr %gep_s1, align 1
  store i32 %load2, ptr %gep_s2, align 1
  store i32 %load3, ptr %gep_s3, align 1
  store i32 %load4, ptr %gep_s4, align 1
  store i32 %load5, ptr %gep_s5, align 1
  store i32 %load6, ptr %gep_s6, align 1
  store i32 %load7, ptr %gep_s7, align 1
  store i32 %load8, ptr %gep_s8, align 1
  store i32 %load9, ptr %gep_s9, align 1
  store i32 %load10, ptr %gep_s10, align 1
  store i32 %load11, ptr %gep_s11, align 1
  store i32 %load12, ptr %gep_s12, align 1
  store i32 %load13, ptr %gep_s13, align 1
  store i32 %load14, ptr %gep_s14, align 1
  store i32 %load15, ptr %gep_s15, align 1

  ret void
}


define void @constant_stride_masked_no_reordering(ptr %pl, i64 %stride, ptr %ps) {
; CHECK-LABEL: define void @constant_stride_masked_no_reordering(
; CHECK-SAME: ptr [[PL:%.*]], i64 [[STRIDE:%.*]], ptr [[PS:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[GEP_L0:%.*]] = getelementptr inbounds i8, ptr [[PL]], i64 0
; CHECK-NEXT:    [[GEP_L4:%.*]] = getelementptr inbounds i8, ptr [[PL]], i64 65
; CHECK-NEXT:    [[GEP_L8:%.*]] = getelementptr inbounds i8, ptr [[PL]], i64 130
; CHECK-NEXT:    [[GEP_L12:%.*]] = getelementptr inbounds i8, ptr [[PL]], i64 195
; CHECK-NEXT:    [[GEP_S0:%.*]] = getelementptr inbounds i16, ptr [[PS]], i64 0
; CHECK-NEXT:    [[TMP1:%.*]] = load <4 x i16>, ptr [[GEP_L0]], align 1
; CHECK-NEXT:    [[TMP2:%.*]] = load <4 x i16>, ptr [[GEP_L4]], align 1
; CHECK-NEXT:    [[TMP3:%.*]] = load <4 x i16>, ptr [[GEP_L8]], align 1
; CHECK-NEXT:    [[TMP4:%.*]] = load <4 x i16>, ptr [[GEP_L12]], align 1
; CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <4 x i16> [[TMP1]], <4 x i16> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <4 x i16> [[TMP2]], <4 x i16> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <4 x i16> [[TMP1]], <4 x i16> [[TMP2]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <4 x i16> [[TMP3]], <4 x i16> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <16 x i16> [[TMP7]], <16 x i16> [[TMP8]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 16, i32 17, i32 18, i32 19, i32 poison, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <4 x i16> [[TMP4]], <4 x i16> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP11:%.*]] = shufflevector <16 x i16> [[TMP9]], <16 x i16> [[TMP10]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 16, i32 17, i32 18, i32 19>
; CHECK-NEXT:    store <16 x i16> [[TMP11]], ptr [[GEP_S0]], align 1
; CHECK-NEXT:    ret void
;
  %gep_l0 = getelementptr inbounds i8, ptr %pl, i64 0
  %gep_l1 = getelementptr inbounds i8, ptr %pl, i64 2
  %gep_l2 = getelementptr inbounds i8, ptr %pl, i64 4
  %gep_l3 = getelementptr inbounds i8, ptr %pl, i64 6
  %gep_l4 = getelementptr inbounds i8, ptr %pl, i64 65
  %gep_l5 = getelementptr inbounds i8, ptr %pl, i64 67
  %gep_l6 = getelementptr inbounds i8, ptr %pl, i64 69
  %gep_l7 = getelementptr inbounds i8, ptr %pl, i64 71
  %gep_l8 = getelementptr inbounds i8, ptr %pl, i64 130
  %gep_l9 = getelementptr inbounds i8, ptr %pl, i64 132
  %gep_l10 = getelementptr inbounds i8, ptr %pl, i64 134
  %gep_l11 = getelementptr inbounds i8, ptr %pl, i64 136
  %gep_l12 = getelementptr inbounds i8, ptr %pl, i64 195
  %gep_l13 = getelementptr inbounds i8, ptr %pl, i64 197
  %gep_l14 = getelementptr inbounds i8, ptr %pl, i64 199
  %gep_l15 = getelementptr inbounds i8, ptr %pl, i64 201

  %load0  = load i16, ptr %gep_l0 , align 1
  %load1  = load i16, ptr %gep_l1 , align 1
  %load2  = load i16, ptr %gep_l2 , align 1
  %load3  = load i16, ptr %gep_l3 , align 1
  %load4  = load i16, ptr %gep_l4 , align 1
  %load5  = load i16, ptr %gep_l5 , align 1
  %load6  = load i16, ptr %gep_l6 , align 1
  %load7  = load i16, ptr %gep_l7 , align 1
  %load8  = load i16, ptr %gep_l8 , align 1
  %load9  = load i16, ptr %gep_l9 , align 1
  %load10 = load i16, ptr %gep_l10, align 1
  %load11 = load i16, ptr %gep_l11, align 1
  %load12 = load i16, ptr %gep_l12, align 1
  %load13 = load i16, ptr %gep_l13, align 1
  %load14 = load i16, ptr %gep_l14, align 1
  %load15 = load i16, ptr %gep_l15, align 1

  %gep_s0 = getelementptr inbounds i16, ptr %ps, i64 0
  %gep_s1 = getelementptr inbounds i16, ptr %ps, i64 1
  %gep_s2 = getelementptr inbounds i16, ptr %ps, i64 2
  %gep_s3 = getelementptr inbounds i16, ptr %ps, i64 3
  %gep_s4 = getelementptr inbounds i16, ptr %ps, i64 4
  %gep_s5 = getelementptr inbounds i16, ptr %ps, i64 5
  %gep_s6 = getelementptr inbounds i16, ptr %ps, i64 6
  %gep_s7 = getelementptr inbounds i16, ptr %ps, i64 7
  %gep_s8 = getelementptr inbounds i16, ptr %ps, i64 8
  %gep_s9 = getelementptr inbounds i16, ptr %ps, i64 9
  %gep_s10 = getelementptr inbounds i16, ptr %ps, i64 10
  %gep_s11 = getelementptr inbounds i16, ptr %ps, i64 11
  %gep_s12 = getelementptr inbounds i16, ptr %ps, i64 12
  %gep_s13 = getelementptr inbounds i16, ptr %ps, i64 13
  %gep_s14 = getelementptr inbounds i16, ptr %ps, i64 14
  %gep_s15 = getelementptr inbounds i16, ptr %ps, i64 15

  store i16 %load0, ptr %gep_s0, align 1
  store i16 %load1, ptr %gep_s1, align 1
  store i16 %load2, ptr %gep_s2, align 1
  store i16 %load3, ptr %gep_s3, align 1
  store i16 %load4, ptr %gep_s4, align 1
  store i16 %load5, ptr %gep_s5, align 1
  store i16 %load6, ptr %gep_s6, align 1
  store i16 %load7, ptr %gep_s7, align 1
  store i16 %load8, ptr %gep_s8, align 1
  store i16 %load9, ptr %gep_s9, align 1
  store i16 %load10, ptr %gep_s10, align 1
  store i16 %load11, ptr %gep_s11, align 1
  store i16 %load12, ptr %gep_s12, align 1
  store i16 %load13, ptr %gep_s13, align 1
  store i16 %load14, ptr %gep_s14, align 1
  store i16 %load15, ptr %gep_s15, align 1

  ret void
}

define void @rt_stride_widen_no_reordering(ptr %pl, i64 %stride, ptr %ps) {
; CHECK-LABEL: define void @rt_stride_widen_no_reordering(
; CHECK-SAME: ptr [[PL:%.*]], i64 [[STRIDE:%.*]], ptr [[PS:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[OFFSET0:%.*]] = mul nsw i64 [[STRIDE]], 0
; CHECK-NEXT:    [[OFFSET4:%.*]] = mul nsw i64 [[STRIDE]], 1
; CHECK-NEXT:    [[OFFSET8:%.*]] = mul nsw i64 [[STRIDE]], 2
; CHECK-NEXT:    [[OFFSET12:%.*]] = mul nsw i64 [[STRIDE]], 3
; CHECK-NEXT:    [[GEP_L0:%.*]] = getelementptr inbounds i8, ptr [[PL]], i64 [[OFFSET0]]
; CHECK-NEXT:    [[GEP_L4:%.*]] = getelementptr inbounds i8, ptr [[PL]], i64 [[OFFSET4]]
; CHECK-NEXT:    [[GEP_L5:%.*]] = getelementptr inbounds i8, ptr [[PL]], i64 2
; CHECK-NEXT:    [[GEP_L6:%.*]] = getelementptr inbounds i8, ptr [[PL]], i64 4
; CHECK-NEXT:    [[GEP_L8:%.*]] = getelementptr inbounds i8, ptr [[PL]], i64 [[OFFSET8]]
; CHECK-NEXT:    [[GEP_L9:%.*]] = getelementptr inbounds i8, ptr [[PL]], i64 2
; CHECK-NEXT:    [[GEP_L10:%.*]] = getelementptr inbounds i8, ptr [[PL]], i64 4
; CHECK-NEXT:    [[GEP_L11:%.*]] = getelementptr inbounds i8, ptr [[PL]], i64 6
; CHECK-NEXT:    [[GEP_L12:%.*]] = getelementptr inbounds i8, ptr [[PL]], i64 [[OFFSET12]]
; CHECK-NEXT:    [[GEP_L13:%.*]] = getelementptr inbounds i8, ptr [[PL]], i64 2
; CHECK-NEXT:    [[GEP_L14:%.*]] = getelementptr inbounds i8, ptr [[PL]], i64 4
; CHECK-NEXT:    [[GEP_L15:%.*]] = getelementptr inbounds i8, ptr [[PL]], i64 6
; CHECK-NEXT:    [[LOAD4:%.*]] = load i16, ptr [[GEP_L4]], align 1
; CHECK-NEXT:    [[LOAD5:%.*]] = load i16, ptr [[GEP_L5]], align 1
; CHECK-NEXT:    [[LOAD8:%.*]] = load i16, ptr [[GEP_L8]], align 1
; CHECK-NEXT:    [[LOAD9:%.*]] = load i16, ptr [[GEP_L9]], align 1
; CHECK-NEXT:    [[LOAD10:%.*]] = load i16, ptr [[GEP_L10]], align 1
; CHECK-NEXT:    [[LOAD11:%.*]] = load i16, ptr [[GEP_L11]], align 1
; CHECK-NEXT:    [[LOAD12:%.*]] = load i16, ptr [[GEP_L12]], align 1
; CHECK-NEXT:    [[LOAD13:%.*]] = load i16, ptr [[GEP_L13]], align 1
; CHECK-NEXT:    [[LOAD14:%.*]] = load i16, ptr [[GEP_L14]], align 1
; CHECK-NEXT:    [[LOAD15:%.*]] = load i16, ptr [[GEP_L15]], align 1
; CHECK-NEXT:    [[GEP_S0:%.*]] = getelementptr inbounds i16, ptr [[PS]], i64 0
; CHECK-NEXT:    [[GEP_S8:%.*]] = getelementptr inbounds i16, ptr [[PS]], i64 8
; CHECK-NEXT:    [[GEP_S9:%.*]] = getelementptr inbounds i16, ptr [[PS]], i64 9
; CHECK-NEXT:    [[GEP_S10:%.*]] = getelementptr inbounds i16, ptr [[PS]], i64 10
; CHECK-NEXT:    [[GEP_S11:%.*]] = getelementptr inbounds i16, ptr [[PS]], i64 11
; CHECK-NEXT:    [[GEP_S12:%.*]] = getelementptr inbounds i16, ptr [[PS]], i64 12
; CHECK-NEXT:    [[GEP_S13:%.*]] = getelementptr inbounds i16, ptr [[PS]], i64 13
; CHECK-NEXT:    [[GEP_S14:%.*]] = getelementptr inbounds i16, ptr [[PS]], i64 14
; CHECK-NEXT:    [[GEP_S15:%.*]] = getelementptr inbounds i16, ptr [[PS]], i64 15
; CHECK-NEXT:    [[TMP1:%.*]] = load <4 x i16>, ptr [[GEP_L0]], align 1
; CHECK-NEXT:    [[TMP2:%.*]] = load <2 x i16>, ptr [[GEP_L6]], align 1
; CHECK-NEXT:    [[TMP3:%.*]] = insertelement <8 x i16> poison, i16 [[LOAD4]], i32 4
; CHECK-NEXT:    [[TMP4:%.*]] = insertelement <8 x i16> [[TMP3]], i16 [[LOAD5]], i32 5
; CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <4 x i16> [[TMP1]], <4 x i16> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 poison, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i16> [[TMP4]], <8 x i16> [[TMP5]], <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <2 x i16> [[TMP2]], <2 x i16> poison, <8 x i32> <i32 0, i32 1, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <8 x i16> [[TMP6]], <8 x i16> [[TMP7]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 8, i32 9>
; CHECK-NEXT:    store <8 x i16> [[TMP8]], ptr [[GEP_S0]], align 1
; CHECK-NEXT:    store i16 [[LOAD8]], ptr [[GEP_S8]], align 1
; CHECK-NEXT:    store i16 [[LOAD9]], ptr [[GEP_S9]], align 1
; CHECK-NEXT:    store i16 [[LOAD10]], ptr [[GEP_S10]], align 1
; CHECK-NEXT:    store i16 [[LOAD11]], ptr [[GEP_S11]], align 1
; CHECK-NEXT:    store i16 [[LOAD12]], ptr [[GEP_S12]], align 1
; CHECK-NEXT:    store i16 [[LOAD13]], ptr [[GEP_S13]], align 1
; CHECK-NEXT:    store i16 [[LOAD14]], ptr [[GEP_S14]], align 1
; CHECK-NEXT:    store i16 [[LOAD15]], ptr [[GEP_S15]], align 1
; CHECK-NEXT:    ret void
;
  %offset0  = mul nsw i64 %stride, 0
  %offset4  = mul nsw i64 %stride, 1
  %offset8  = mul nsw i64 %stride, 2
  %offset12 = mul nsw i64 %stride, 3

  %gep_l0 = getelementptr inbounds i8, ptr %pl, i64 %offset0
  %gep_l1 = getelementptr inbounds i8, ptr %pl, i64 2
  %gep_l2 = getelementptr inbounds i8, ptr %pl, i64 4
  %gep_l3 = getelementptr inbounds i8, ptr %pl, i64 6
  %gep_l4 = getelementptr inbounds i8, ptr %pl, i64 %offset4
  %gep_l5 = getelementptr inbounds i8, ptr %gep_l4, i64 2
  %gep_l6 = getelementptr inbounds i8, ptr %gep_l4, i64 4
  %gep_l7 = getelementptr inbounds i8, ptr %gep_l4, i64 6
  %gep_l8 = getelementptr inbounds i8, ptr %pl, i64 %offset8
  %gep_l9 = getelementptr inbounds i8, ptr %gep_l8, i64 2
  %gep_l10 = getelementptr inbounds i8, ptr %gep_l8, i64 4
  %gep_l11 = getelementptr inbounds i8, ptr %gep_l8, i64 6
  %gep_l12 = getelementptr inbounds i8, ptr %pl, i64 %offset12
  %gep_l13 = getelementptr inbounds i8, ptr %gep_l12, i64 2
  %gep_l14 = getelementptr inbounds i8, ptr %gep_l12, i64 4
  %gep_l15 = getelementptr inbounds i8, ptr %gep_l12, i64 6

  %load0  = load i16, ptr %gep_l0 , align 1
  %load1  = load i16, ptr %gep_l1 , align 1
  %load2  = load i16, ptr %gep_l2 , align 1
  %load3  = load i16, ptr %gep_l3 , align 1
  %load4  = load i16, ptr %gep_l4 , align 1
  %load5  = load i16, ptr %gep_l5 , align 1
  %load6  = load i16, ptr %gep_l6 , align 1
  %load7  = load i16, ptr %gep_l7 , align 1
  %load8  = load i16, ptr %gep_l8 , align 1
  %load9  = load i16, ptr %gep_l9 , align 1
  %load10 = load i16, ptr %gep_l10, align 1
  %load11 = load i16, ptr %gep_l11, align 1
  %load12 = load i16, ptr %gep_l12, align 1
  %load13 = load i16, ptr %gep_l13, align 1
  %load14 = load i16, ptr %gep_l14, align 1
  %load15 = load i16, ptr %gep_l15, align 1

  %gep_s0 = getelementptr inbounds i16, ptr %ps, i64 0
  %gep_s1 = getelementptr inbounds i16, ptr %ps, i64 1
  %gep_s2 = getelementptr inbounds i16, ptr %ps, i64 2
  %gep_s3 = getelementptr inbounds i16, ptr %ps, i64 3
  %gep_s4 = getelementptr inbounds i16, ptr %ps, i64 4
  %gep_s5 = getelementptr inbounds i16, ptr %ps, i64 5
  %gep_s6 = getelementptr inbounds i16, ptr %ps, i64 6
  %gep_s7 = getelementptr inbounds i16, ptr %ps, i64 7
  %gep_s8 = getelementptr inbounds i16, ptr %ps, i64 8
  %gep_s9 = getelementptr inbounds i16, ptr %ps, i64 9
  %gep_s10 = getelementptr inbounds i16, ptr %ps, i64 10
  %gep_s11 = getelementptr inbounds i16, ptr %ps, i64 11
  %gep_s12 = getelementptr inbounds i16, ptr %ps, i64 12
  %gep_s13 = getelementptr inbounds i16, ptr %ps, i64 13
  %gep_s14 = getelementptr inbounds i16, ptr %ps, i64 14
  %gep_s15 = getelementptr inbounds i16, ptr %ps, i64 15

  store i16 %load0, ptr %gep_s0, align 1
  store i16 %load1, ptr %gep_s1, align 1
  store i16 %load2, ptr %gep_s2, align 1
  store i16 %load3, ptr %gep_s3, align 1
  store i16 %load4, ptr %gep_s4, align 1
  store i16 %load5, ptr %gep_s5, align 1
  store i16 %load6, ptr %gep_s6, align 1
  store i16 %load7, ptr %gep_s7, align 1
  store i16 %load8, ptr %gep_s8, align 1
  store i16 %load9, ptr %gep_s9, align 1
  store i16 %load10, ptr %gep_s10, align 1
  store i16 %load11, ptr %gep_s11, align 1
  store i16 %load12, ptr %gep_s12, align 1
  store i16 %load13, ptr %gep_s13, align 1
  store i16 %load14, ptr %gep_s14, align 1
  store i16 %load15, ptr %gep_s15, align 1

  ret void
}
