; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5

; RUN: opt -mtriple=riscv64 -mattr=+m,+v,+unaligned-vector-mem -passes=slp-vectorizer -slp-revec -S < %s | FileCheck %s

define void @unaligned_const_stride(ptr %pl, ptr %ps) {
; CHECK-LABEL: define void @unaligned_const_stride(
; CHECK-SAME: ptr [[PL:%.*]], ptr [[PS:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    [[TMP1:%.*]] = insertelement <8 x ptr> poison, ptr [[PL]], i32 0
; CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x ptr> [[TMP1]], <8 x ptr> poison, <8 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, <8 x ptr> [[TMP2]], <8 x i64> <i64 0, i64 65, i64 130, i64 195, i64 260, i64 325, i64 390, i64 455>
; CHECK-NEXT:    [[GEP_S0:%.*]] = getelementptr inbounds i16, ptr [[PS]], i64 0
; CHECK-NEXT:    [[TMP4:%.*]] = call <8 x i16> @llvm.masked.gather.v8i16.v8p0(<8 x ptr> align 1 [[TMP3]], <8 x i1> splat (i1 true), <8 x i16> poison)
; CHECK-NEXT:    store <8 x i16> [[TMP4]], ptr [[GEP_S0]], align 1
; CHECK-NEXT:    ret void
;
  %gep_l0 = getelementptr inbounds i8, ptr %pl, i64 0
  %gep_l1 = getelementptr inbounds i8, ptr %pl, i64 65
  %gep_l2 = getelementptr inbounds i8, ptr %pl, i64 130
  %gep_l3 = getelementptr inbounds i8, ptr %pl, i64 195
  %gep_l4 = getelementptr inbounds i8, ptr %pl, i64 260
  %gep_l5 = getelementptr inbounds i8, ptr %pl, i64 325
  %gep_l6 = getelementptr inbounds i8, ptr %pl, i64 390
  %gep_l7 = getelementptr inbounds i8, ptr %pl, i64 455

  %load0  = load i16, ptr %gep_l0 , align 1
  %load1  = load i16, ptr %gep_l1 , align 1
  %load2  = load i16, ptr %gep_l2 , align 1
  %load3  = load i16, ptr %gep_l3 , align 1
  %load4  = load i16, ptr %gep_l4 , align 1
  %load5  = load i16, ptr %gep_l5 , align 1
  %load6  = load i16, ptr %gep_l6 , align 1
  %load7  = load i16, ptr %gep_l7 , align 1

  %gep_s0 = getelementptr inbounds i16, ptr %ps, i64 0
  %gep_s1 = getelementptr inbounds i16, ptr %ps, i64 1
  %gep_s2 = getelementptr inbounds i16, ptr %ps, i64 2
  %gep_s3 = getelementptr inbounds i16, ptr %ps, i64 3
  %gep_s4 = getelementptr inbounds i16, ptr %ps, i64 4
  %gep_s5 = getelementptr inbounds i16, ptr %ps, i64 5
  %gep_s6 = getelementptr inbounds i16, ptr %ps, i64 6
  %gep_s7 = getelementptr inbounds i16, ptr %ps, i64 7

  store i16 %load0, ptr %gep_s0, align 1
  store i16 %load1, ptr %gep_s1, align 1
  store i16 %load2, ptr %gep_s2, align 1
  store i16 %load3, ptr %gep_s3, align 1
  store i16 %load4, ptr %gep_s4, align 1
  store i16 %load5, ptr %gep_s5, align 1
  store i16 %load6, ptr %gep_s6, align 1
  store i16 %load7, ptr %gep_s7, align 1

  ret void
}

define void @unaligned_const_stride_revec(ptr %pl, ptr %ps) {
; CHECK-LABEL: define void @unaligned_const_stride_revec(
; CHECK-SAME: ptr [[PL:%.*]], ptr [[PS:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[GEP_L0:%.*]] = getelementptr inbounds i8, ptr [[PL]], i64 0
; CHECK-NEXT:    [[GEP_L1:%.*]] = getelementptr inbounds i8, ptr [[PL]], i64 16
; CHECK-NEXT:    [[LOAD0:%.*]] = load <4 x i16>, ptr [[GEP_L0]], align 1
; CHECK-NEXT:    [[LOAD1:%.*]] = load <4 x i16>, ptr [[GEP_L1]], align 1
; CHECK-NEXT:    [[GEP_S0:%.*]] = getelementptr inbounds i8, ptr [[PS]], i64 0
; CHECK-NEXT:    [[GEP_S1:%.*]] = getelementptr inbounds i8, ptr [[PS]], i64 4
; CHECK-NEXT:    store <4 x i16> [[LOAD0]], ptr [[GEP_S0]], align 1
; CHECK-NEXT:    store <4 x i16> [[LOAD1]], ptr [[GEP_S1]], align 1
; CHECK-NEXT:    ret void
;
  %gep_l0 = getelementptr inbounds i8, ptr %pl, i64 0
  %gep_l1 = getelementptr inbounds i8, ptr %pl, i64 16

  %load0  = load <4 x i16>, ptr %gep_l0 , align 1
  %load1  = load <4 x i16>, ptr %gep_l1 , align 1

  %gep_s0 = getelementptr inbounds i8, ptr %ps, i64 0
  %gep_s1 = getelementptr inbounds i8, ptr %ps, i64 4

  store <4 x i16> %load0, ptr %gep_s0, align 1
  store <4 x i16> %load1, ptr %gep_s1, align 1

  ret void
}

define void @unaligned_const_stride_revec_same_scalar_type(ptr %pl, ptr %ps) {
; CHECK-LABEL: define void @unaligned_const_stride_revec_same_scalar_type(
; CHECK-SAME: ptr [[PL:%.*]], ptr [[PS:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[GEP_L0:%.*]] = getelementptr inbounds i8, ptr [[PL]], i64 0
; CHECK-NEXT:    [[GEP_L1:%.*]] = getelementptr inbounds i8, ptr [[PL]], i64 17
; CHECK-NEXT:    [[LOAD0:%.*]] = load <8 x i8>, ptr [[GEP_L0]], align 1
; CHECK-NEXT:    [[LOAD1:%.*]] = load <8 x i8>, ptr [[GEP_L1]], align 1
; CHECK-NEXT:    [[GEP_S0:%.*]] = getelementptr inbounds i8, ptr [[PS]], i64 0
; CHECK-NEXT:    [[GEP_S1:%.*]] = getelementptr inbounds i8, ptr [[PS]], i64 8
; CHECK-NEXT:    store <8 x i8> [[LOAD0]], ptr [[GEP_S0]], align 1
; CHECK-NEXT:    store <8 x i8> [[LOAD1]], ptr [[GEP_S1]], align 1
; CHECK-NEXT:    ret void
;
  %gep_l0 = getelementptr inbounds i8, ptr %pl, i64 0
  %gep_l1 = getelementptr inbounds i8, ptr %pl, i64 17

  %load0  = load <8 x i8>, ptr %gep_l0 , align 1
  %load1  = load <8 x i8>, ptr %gep_l1 , align 1

  %gep_s0 = getelementptr inbounds i8, ptr %ps, i64 0
  %gep_s1 = getelementptr inbounds i8, ptr %ps, i64 8

  store <8 x i8> %load0, ptr %gep_s0, align 1
  store <8 x i8> %load1, ptr %gep_s1, align 1

  ret void
}

define void @unaligned_rt_stride(ptr %pl, ptr %ps, i64 %stride) {
; CHECK-LABEL: define void @unaligned_rt_stride(
; CHECK-SAME: ptr [[PL:%.*]], ptr [[PS:%.*]], i64 [[STRIDE:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[GEP_L0:%.*]] = getelementptr inbounds i8, ptr [[PL]], i64 0
; CHECK-NEXT:    [[GEP_S0:%.*]] = getelementptr inbounds i16, ptr [[PS]], i64 0
; CHECK-NEXT:    [[TMP1:%.*]] = mul i64 [[STRIDE]], 1
; CHECK-NEXT:    [[TMP2:%.*]] = call <8 x i16> @llvm.experimental.vp.strided.load.v8i16.p0.i64(ptr align 1 [[GEP_L0]], i64 [[TMP1]], <8 x i1> splat (i1 true), i32 8)
; CHECK-NEXT:    store <8 x i16> [[TMP2]], ptr [[GEP_S0]], align 1
; CHECK-NEXT:    ret void
;
  %gep_l0 = getelementptr inbounds i8, ptr %pl, i64 0
  %gep_l1 = getelementptr inbounds i8, ptr %gep_l0, i64 %stride
  %gep_l2 = getelementptr inbounds i8, ptr %gep_l1, i64 %stride
  %gep_l3 = getelementptr inbounds i8, ptr %gep_l2, i64 %stride
  %gep_l4 = getelementptr inbounds i8, ptr %gep_l3, i64 %stride
  %gep_l5 = getelementptr inbounds i8, ptr %gep_l4, i64 %stride
  %gep_l6 = getelementptr inbounds i8, ptr %gep_l5, i64 %stride
  %gep_l7 = getelementptr inbounds i8, ptr %gep_l6, i64 %stride

  %load0  = load i16, ptr %gep_l0 , align 1
  %load1  = load i16, ptr %gep_l1 , align 1
  %load2  = load i16, ptr %gep_l2 , align 1
  %load3  = load i16, ptr %gep_l3 , align 1
  %load4  = load i16, ptr %gep_l4 , align 1
  %load5  = load i16, ptr %gep_l5 , align 1
  %load6  = load i16, ptr %gep_l6 , align 1
  %load7  = load i16, ptr %gep_l7 , align 1

  %gep_s0 = getelementptr inbounds i16, ptr %ps, i64 0
  %gep_s1 = getelementptr inbounds i16, ptr %ps, i64 1
  %gep_s2 = getelementptr inbounds i16, ptr %ps, i64 2
  %gep_s3 = getelementptr inbounds i16, ptr %ps, i64 3
  %gep_s4 = getelementptr inbounds i16, ptr %ps, i64 4
  %gep_s5 = getelementptr inbounds i16, ptr %ps, i64 5
  %gep_s6 = getelementptr inbounds i16, ptr %ps, i64 6
  %gep_s7 = getelementptr inbounds i16, ptr %ps, i64 7

  store i16 %load0, ptr %gep_s0, align 1
  store i16 %load1, ptr %gep_s1, align 1
  store i16 %load2, ptr %gep_s2, align 1
  store i16 %load3, ptr %gep_s3, align 1
  store i16 %load4, ptr %gep_s4, align 1
  store i16 %load5, ptr %gep_s5, align 1
  store i16 %load6, ptr %gep_s6, align 1
  store i16 %load7, ptr %gep_s7, align 1

  ret void
}

define void @unaligned_rt_stride_revec(ptr %pl, ptr %ps, i64 %stride) {
; CHECK-LABEL: define void @unaligned_rt_stride_revec(
; CHECK-SAME: ptr [[PL:%.*]], ptr [[PS:%.*]], i64 [[STRIDE:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[GEP_L0:%.*]] = getelementptr inbounds i8, ptr [[PL]], i64 0
; CHECK-NEXT:    [[GEP_S0:%.*]] = getelementptr inbounds i8, ptr [[PS]], i64 0
; CHECK-NEXT:    [[TMP1:%.*]] = mul i64 [[STRIDE]], 1
; CHECK-NEXT:    [[TMP2:%.*]] = call <2 x i64> @llvm.experimental.vp.strided.load.v2i64.p0.i64(ptr align 1 [[GEP_L0]], i64 [[TMP1]], <2 x i1> splat (i1 true), i32 2)
; CHECK-NEXT:    [[TMP3:%.*]] = bitcast <2 x i64> [[TMP2]] to <8 x i16>
; CHECK-NEXT:    store <8 x i16> [[TMP3]], ptr [[GEP_S0]], align 1
; CHECK-NEXT:    ret void
;
  %gep_l0 = getelementptr inbounds i8, ptr %pl, i64 0
  %gep_l1 = getelementptr inbounds i8, ptr %pl, i64 %stride

  %load0  = load <4 x i16>, ptr %gep_l0 , align 1
  %load1  = load <4 x i16>, ptr %gep_l1 , align 1

  %gep_s0 = getelementptr inbounds i8, ptr %ps, i64 0
  %gep_s1 = getelementptr inbounds i8, ptr %ps, i64 8

  store <4 x i16> %load0, ptr %gep_s0, align 1
  store <4 x i16> %load1, ptr %gep_s1, align 1

  ret void
}

define void @unaligned_rt_stride_revec_same_scalar_type(ptr %pl, ptr %ps, i64 %stride) {
; CHECK-LABEL: define void @unaligned_rt_stride_revec_same_scalar_type(
; CHECK-SAME: ptr [[PL:%.*]], ptr [[PS:%.*]], i64 [[STRIDE:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[GEP_L0:%.*]] = getelementptr inbounds i8, ptr [[PL]], i64 0
; CHECK-NEXT:    [[GEP_S0:%.*]] = getelementptr inbounds i8, ptr [[PS]], i64 0
; CHECK-NEXT:    [[TMP1:%.*]] = mul i64 [[STRIDE]], 1
; CHECK-NEXT:    [[TMP2:%.*]] = call <2 x i64> @llvm.experimental.vp.strided.load.v2i64.p0.i64(ptr align 1 [[GEP_L0]], i64 [[TMP1]], <2 x i1> splat (i1 true), i32 2)
; CHECK-NEXT:    [[TMP3:%.*]] = bitcast <2 x i64> [[TMP2]] to <16 x i8>
; CHECK-NEXT:    store <16 x i8> [[TMP3]], ptr [[GEP_S0]], align 1
; CHECK-NEXT:    ret void
;
  %gep_l0 = getelementptr inbounds i8, ptr %pl, i64 0
  %gep_l1 = getelementptr inbounds i8, ptr %pl, i64 %stride

  %load0  = load <8 x i8>, ptr %gep_l0 , align 1
  %load1  = load <8 x i8>, ptr %gep_l1 , align 1

  %gep_s0 = getelementptr inbounds i8, ptr %ps, i64 0
  %gep_s1 = getelementptr inbounds i8, ptr %ps, i64 8

  store <8 x i8> %load0, ptr %gep_s0, align 1
  store <8 x i8> %load1, ptr %gep_s1, align 1

  ret void
}
