; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes="function(scalable-to-fixed-vectors)" -S %s | FileCheck %s

define void @cast_fold(ptr %dst) vscale_range(2,4) {
; CHECK-LABEL: define void @cast_fold(
; CHECK-SAME: ptr [[DST:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    store <4 x i8> zeroinitializer, ptr [[DST]], align 4
; CHECK-NEXT:    ret void
;
  %zext = zext <vscale x 16 x i8> zeroinitializer to <vscale x 16 x i16>
  %lshr = lshr <vscale x 16 x i16> %zext, splat (i16 1)
  %trunc = trunc nuw <vscale x 16 x i16> %lshr to <vscale x 16 x i8>
  call void @llvm.vp.store.nxv4i32.p0(<vscale x 16 x i8> %trunc, ptr %dst, <vscale x 16 x i1> splat (i1 true), i32 4)
  ret void
}

define void @iss164762(ptr %dst, ptr %src0, ptr %src1) vscale_range(2,4) {
; CHECK-LABEL: define void @iss164762(
; CHECK-SAME: ptr [[DST:%.*]], ptr [[SRC0:%.*]], ptr [[SRC1:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[LOAD0:%.*]] = load <4 x i8>, ptr [[SRC0]], align 1
; CHECK-NEXT:    [[ZEXT0:%.*]] = zext <4 x i8> [[LOAD0]] to <4 x i16>
; CHECK-NEXT:    [[ADD0:%.*]] = add nuw nsw <4 x i16> [[ZEXT0]], splat (i16 1)
; CHECK-NEXT:    [[LOAD1:%.*]] = load <4 x i8>, ptr [[SRC1]], align 1
; CHECK-NEXT:    [[ZEXT1:%.*]] = zext <4 x i8> [[LOAD1]] to <4 x i16>
; CHECK-NEXT:    [[ADD1:%.*]] = add nuw nsw <4 x i16> [[ADD0]], [[ZEXT1]]
; CHECK-NEXT:    [[LSHR:%.*]] = lshr <4 x i16> [[ADD1]], splat (i16 1)
; CHECK-NEXT:    [[TRUNC:%.*]] = trunc nuw <4 x i16> [[LSHR]] to <4 x i8>
; CHECK-NEXT:    store <4 x i8> [[TRUNC]], ptr [[DST]], align 4
; CHECK-NEXT:    ret void
;
  %load0 = tail call <vscale x 16 x i8> @llvm.vp.load.nxv16i8.p0(ptr align 1 %src0, <vscale x 16 x i1> splat (i1 true), i32 4)
  %zext0 = zext <vscale x 16 x i8> %load0 to <vscale x 16 x i16>
  %add0 = add nuw nsw <vscale x 16 x i16> %zext0, splat (i16 1)

  %load1 = tail call <vscale x 16 x i8> @llvm.vp.load.nxv16i8.p0(ptr align 1 %src1, <vscale x 16 x i1> splat (i1 true), i32 4)
  %zext1 = zext <vscale x 16 x i8> %load1 to <vscale x 16 x i16>

  %add1 = add nuw nsw <vscale x 16 x i16> %add0, %zext1
  %lshr = lshr <vscale x 16 x i16> %add1, splat (i16 1)
  %trunc = trunc nuw <vscale x 16 x i16> %lshr to <vscale x 16 x i8>
  call void @llvm.vp.store.nxv4i32.p0(<vscale x 16 x i8> %trunc, ptr %dst, <vscale x 16 x i1> splat (i1 true), i32 4)
  ret void
}

